name: Test
on: [push]
jobs:
  on_build_actions:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: | 
            cd $GITHUB_WORKSPACE
            #python -m pip install --upgrade pip
            #pip install -r requirements.txt
        - name: Run Tests
          run: python -m unittest tests/*.py
        - name: Generate Report
          run: |
            pip install codecov
            pip install pytest-cov
            pytest --cov=./ --cov-report=xml
            codecov
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3